version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: jobportal_frontend
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:5000
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.backend
    container_name: jobportal_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://chijithjerin_db_user:Y7ojh6iJZXdKvOf8@hacklehem.76wdx41.mongodb.net/?retryWrites=true&w=majority&appName=Hacklehem
      - CLOUDINARY_URL=cloudinary://211162944598199:O-u33XKphDdIx1cOf5lEyDxSzH8@dj0pydhla
    volumes:
      - ./server:/server
      - /server/node_modules
